---
- name: Disable k8s systemd daemons
  service:
    name: "{{item}}"
    enabled: no
    state: stopped
  with_items: "{{k8s_daemons}}"
  notify:
    - Restart etcd
  when: master

- meta: flush_handlers

- name: k8s services enabled and started
  service:
    name: "{{item}}"
    enabled: yes
    state: started
  with_items: "{{k8s_node_services}}"

